openapi: 3.1.3
info:
  version: 0.0.1
  title: WDCC Membership Checker
  license:
    name: private
    url: about:blank
  contact:
    email: projects@wdcc.co.nz
    url: wdcc.co.nz

paths:
  '/':
    get:
      security:
        - jwt_token:
            - 'read:users'
      operationId: index
      description: |
        Respond with "Hello, {firstName}!" if the user is signed in and Hello, World! if the user is not signed in with
      tags:
        - User
      summary: Respond with "Hello, {firstName}!" if the user is signed in and Hello, World! if the user is not signed in
      servers: []
      responses:
        200:
          description: 'OK'
          content:
            application/text:
              schema:
                type: string
              examples:
                example1:
                  value: 'Hello, Alex!'
                example2:
                  value: 'Hello, World!'

        400:
          description: 'BAD REQUEST'
  '/auth/google':
    $ref: './routes/auth/redirect.yaml'
  '/auth/google/callback':
    $ref: './routes/auth/callback.yaml'
  '/club/create':
    $ref: './routes/club/create.yaml'
servers:
  - url: about:blank
components:
  securitySchemes:
    jwt_token:
      description: Generated when you sign in
      type: http
      scheme: bearer
      bearerFormat: JWT
