openapi: 3.1.3
info:
  version: 0.0.1
  title: WDCC Membership Checker
  license:
    name: private
    url: about:blank
  contact:
    email: projects@wdcc.co.nz
    url: wdcc.co.nz
paths:
  '/':
    $ref: './paths/index.yaml'
servers:
  - url: about:blank
components:
  securitySchemes:
    jwt_token:
      description: Generated when you sign in
      type: http
      scheme: bearer
      bearerFormat: JWT
